### ISSUE TITLE
Rename and publish

### ISSUE THREAD

**Issue by kasperisager** [sodium-friends/react-native-libsodium#14]
Can we rename this project `sodium-react-native` and publish it to npm? I've opened a PR in `sodium-universal` to pull in this module on React Native: https://github.com/sodium-friends/sodium-universal/pull/8

**Comment by chm-diederichs** [comment]
We should also rename this dir to `android/src/main/java/com/sodiumreactnative`

**Comment by chm-diederichs** [comment]
> This package name should be changed:
> 
> https://github.com/sodium-friends/react-native-libsodium/blob/6fbfee572fdfde7e7eec7a1956951d106b342145/android/src/main/java/com/reactnativelibsodium/rn/SodiumModule.java#L1

Here as well: https://github.com/sodium-friends/react-native-libsodium/blob/6fbfee572fdfde7e7eec7a1956951d106b342145/android/src/main/java/com/reactnativelibsodium/rn/SodiumPackage.java#L1
